version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - cd website_backend/
        - yarn install
        - npm install -g @aws-amplify/cli@4.11.0
        - cd ..
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplify -v
        - export NODE_PATH=./node_modules
        - amplifyPush --simple
        - cd ..
  cache:
    paths:
      - website_backend/node_modules/**/*
frontend:
  phases:
    preBuild:
      commands:
        - cd website_backend/
        - yarn install
        - cd ..
    build:
      commands:
        - cd website_backend/ 
        - yarn run build
        - cd ..
  artifacts:
    baseDirectory: website_backend/build
    files:
      - '**/*'
  cache:
    paths:
      - website_backend/node_modules/**/*
